[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ome-zarr-open-scivis-datasets"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
