[project]
authors = ["Matt McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
description = "OME-Zarr Open SciVis Datasets"
name = "ome-zarr-open-scivis-datasets"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
download = { cmd = "python scripts/download.py", description = "Download the Open SciVis Datasets" }

[dependencies]
python = ">=3.12.5,<4"

[pypi-dependencies]
httpx = ">=0.27.2, <0.28"
ngff-zarr = ">=0.8.7, <0.9"
rich = ">=13.8.0, <14"
numpy = ">=2.1.1, <3"
